# Generated by Django 4.1.6 on 2023-02-05 14:01

import django.core.validators
from django.db import migrations, models
import re
import validations.validators.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('even_field', models.IntegerField(validators=[validations.validators.validators.validate_even])),
                ('age_child', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(18, message='Ребенок должен быть не старше 18 лет')], verbose_name='Возраст ребенка')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='Введите строку', regex='^\\D+$')], verbose_name='Имя')),
                ('min_length', models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=10, message='Минимум 10 символов')], verbose_name='min_length')),
                ('max_length', models.TextField(validators=[django.core.validators.MaxLengthValidator(limit_value=10, message='Максимум 10 символов')], verbose_name='max_length')),
            ],
        ),
    ]
